services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bundles\CoreBundle\:
    resource: '../../../../../src/Bundles/CoreBundle/*'
    exclude: '../../../../../src/Bundles/CoreBundle/{Resources}'

  Domain\Core\:
    resource: '../../../../../src/Domain/Core/*'
  Domain\Core\Event\EventListenerProviderInterface:
    class: Domain\Core\Event\EventListenerProvider
  Domain\Core\Event\EventBusInterface:
    class: Domain\Core\Event\EventBus
  Domain\Core\CommandBus\CommandHandlerProviderInterface:
    class: Domain\Core\CommandBus\CommandHandlerProvider
    #Domain\Core\CommandBus\CommandBusInterface:
    #class: Domain\Core\CommandBus\CommandBus