services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bundles\CoreBundle\:
    resource: '../../../../../src/Bundles/CoreBundle/*'
    exclude: '../../../../../src/Bundles/CoreBundle/{Resources}'

  Domain\Core\:
    resource: '../../../../../src/Domain/Core/*'

  Bundles\CoreBundle\EventListener\LocaleSubscriber:
    arguments: ['%kernel.default_locale%']


  Domain\Core\Event\EventListenerProviderInterface:
    class: Domain\Core\Event\EventListenerProvider

  Domain\Core\Event\EventBusInterface:
    class: Domain\Core\Event\EventBus

  Domain\Core\CommandBus\CommandHandlerProviderInterface:
    class: Domain\Core\CommandBus\CommandHandlerProvider

  Domain\Core\QueryBus\QueryHandlerProviderInterface:
    class: Domain\Core\QueryBus\QueryHandlerProvider

  ## alias

  domain.command_handler_provider:
    alias: Domain\Core\CommandBus\CommandHandlerProviderInterface

  domain.query_handler_provider:
    alias: Domain\Core\QueryBus\QueryHandlerProviderInterface
