services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bundles\CustomerBundle\:
    resource: '../../../../../src/Bundles/CustomerBundle/*'
    exclude: '../../../../../src/Bundles/CustomerBundle/{Resources}'
  Domain\Customer\:
    resource: '../../../../../src/Domain/Customer/*'

  Domain\Customer\Signature\CustomerFactoryInterface:
    class: Bundles\CustomerBundle\Factory\CustomerFactory
  Domain\Customer\Signature\CustomerRepositoryInterface:
    class: Bundles\CustomerBundle\Repository\ShopUserRepository