front_home:
  path: /{_locale}
  controller: Application\Front\Controller\HomeController::default
  methods: ['get']



front_cart_page:
  path:
    fr: /{_locale}/votre-panier
    en: /{_locale}/cart
  controller: Application\Front\Controller\CartPageController::index
  methods: ['get']

front_cart_add:
  path: /cart/add
  controller: Application\Front\Controller\CartController::addToCart
  methods: ['post']
front_cart_remove:
  path: /cart/remove
  controller: Application\Front\Controller\CartController::removeFromCart
  methods: ['post']
front_cart_clear:
  path: /cart/clear
  controller: Application\Front\Controller\CartController::clearCart
  methods: ['post']

####### security
front_security_login:
  path: /connexion
  controller: Application\Front\Controller\SecurityController::login
  methods: ['get','post']

front_security_logout:
  path: /deconnexion
  controller: Application\Front\Controller\SecurityController::logout
  methods: ['get']

########## customer account
front_customer_index:
  path:
    fr: /{_locale}/votre-compte
    en: /{_locale}/your-account
  controller: Application\Front\Controller\CustomerAccountController::index
  methods: ['get', 'post']

front_customer_addresses:
  path:
    fr: /{_locale}/vos-adresses
    en: /{_locale}/your-addresses
  controller: Application\Front\Controller\CustomerAccountController::addresses
  methods: ['get', 'post']

front_customer_add_addresse:
  path:
    fr: /{_locale}/ajouter-une-adresse
    en: /{_locale}/add-an-address
  controller: Application\Front\Controller\CustomerAccountController::addAddress
  methods: ['get', 'post']
