front_home:
  path: /{_locale}
  controller: Application\Front\Controller\HomeController::default
  methods: ['get']

front_cart_page:
  path:
    fr: /{_locale}/votre-panier
    en: /{_locale}/cart
  controller: Application\Front\Controller\CartPageController::index
  methods: ['get']

front_cart_add:
  path: /cart/add
  controller: Application\Front\Controller\CartController::addToCart
  methods: ['post']

front_cart_remove:
  path: /cart/remove
  controller: Application\Front\Controller\CartController::removeFromCart
  methods: ['post']

front_cart_clear:
  path: /cart/clear
  controller: Application\Front\Controller\CartController::clearCart
  methods: ['post']

####### security
front_security_login:
  path: /connexion
  controller: Application\Front\Controller\SecurityController::login
  methods: ['get','post']

front_security_logout:
  path: /deconnexion
  controller: Application\Front\Controller\SecurityController::logout
  methods: ['get']

front_security_google_connect:
  path: /connexion/google
  controller: Application\Front\Controller\SecurityController::googleLogin
  methods: ['get']

front_security_google_connect_callback:
  path: /connexion/google/callback
  controller: Application\Front\Controller\SecurityController::googleLoginCallback
  methods: ['get']

########## customer account
front_customer_index:
  path:
    fr: /{_locale}/votre-compte
    en: /{_locale}/your-account
  controller: Application\Front\Controller\CustomerAccountController::index
  methods: ['get', 'post']

front_customer_registration:
  path:
    fr: /{_locale}/creer-un-compte
    en: /{_locale}/create-account
  controller: Application\Front\Controller\CustomerRegistrationController
  methods: ['get', 'post']

front_customer_addresses:
  path:
    fr: /{_locale}/vos-adresses
    en: /{_locale}/your-addresses
  controller: Application\Front\Controller\CustomerAccountController::addresses
  methods: ['get', 'post']

front_customer_add_address:
  path:
    fr: /{_locale}/ajouter-une-adresse
    en: /{_locale}/add-an-address
  controller: Application\Front\Controller\CustomerAccountController::addAddress
  methods: ['get', 'post']

front_customer_remove_address:
  path:
    fr: /{_locale}/supprimer-une-adresse/{id}
    en: /{_locale}/remove-an-address/{id}
  controller: Application\Front\Controller\CustomerAccountController::removeAddress
  methods: ['get']
  requirements:
    id: '[a-z0-9]{8,8}-[a-z0-9]{4,4}-[a-z0-9]{4,4}-[a-z0-9]{4,4}-[a-z0-9]{12,12}'

front_customer_mark_address_billing:
  path:
    fr: /{_locale}/nouvelle-adresse-de-facturation/{id}
    en: /{_locale}/new-billing-address/{id}
  controller: Application\Front\Controller\CustomerAccountController::makeAddressAsBilling
  methods: ['get']
  requirements:
    id: '[a-z0-9]{8,8}-[a-z0-9]{4,4}-[a-z0-9]{4,4}-[a-z0-9]{4,4}-[a-z0-9]{12,12}'

front_customer_mark_address_delivery:
  path:
    fr: /{_locale}/nouvelle-adresse-de-livraison/{id}
    en: /{_locale}/new-delivery-address/{id}
  controller: Application\Front\Controller\CustomerAccountController::makeAddressAsDelivery
  methods: ['get']
  requirements:
    id: '[a-z0-9]{8,8}-[a-z0-9]{4,4}-[a-z0-9]{4,4}-[a-z0-9]{4,4}-[a-z0-9]{12,12}'

front_order_checkout:
  path:
    fr: /{_locale}/passer-commande
    en: /{_locale}/order-checkout
  controller: Application\Front\Controller\OrderController::index
  methods: ['get']
