services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Domain\Core\Bundle\:
    resource: '../../../../../../src/Domain/Core/Bundle/*'
    exclude: '../../../../../../src/Domain/Core/Bundle/{Resources}'
