services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Domain\Product\Bundle\:
    resource: '../../../../../../src/Domain/Product/Bundle/*'
    exclude: '../../../../../../src/Domain/Product/Bundle/{Resources}'

  Domain\Product\Signature\ProductRepositoryInterface:
    class: Domain\Product\Bundle\Repository\ProductRepository
