services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Domain\Cart\Bundle\:
    resource: '../../../../../../src/Domain/Cart/Bundle/*'
    exclude: '../../../../../../src/Domain/Cart/Bundle/{Resources}'

  Domain\Cart\Signature\CartInterface:
    class: Domain\Cart\Bundle\Service\SessionCart
