services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Bundles\AddressBundle\:
    resource: '../../../../../src/Bundles/AddressBundle/*'
    exclude: '../../../../../src/Bundles/AddressBundle/{Resources}'
  Domain\Address\:
    resource: '../../../../../src/Domain/Address/*'

  Domain\Address\Signature\AddressRepositoryInterface:
    class: Bundles\AddressBundle\Repository\AddressRepository
